language: node_js
node_js: stable
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
before_install:
- sh -e /etc/init.d/xvfb start
- npm i -g get-firefox
- cd ..
- get-firefox -ecb unbranded-release
- cd $TRAVIS_BUILD_DIR
