blank_issues_enabled: false
contact_links:
  - name: Discourse Support Thread
    url: https://discourse.mozilla.org/t/support-notification-sound/23758/47
    about: Support thread for troubleshooting and such.
